INSERT INTO products (name, price, create_at) VALUES ('Panasonic', 800, NOW());
INSERT INTO products (name, price, create_at) VALUES ('Sonny', 700, NOW());
INSERT INTO products (name, price, create_at) VALUES ('Apple', 1000, NOW());
INSERT INTO products (name, price, create_at) VALUES ('Hp', 500, NOW());
INSERT INTO products (name, price, create_at) VALUES ('Dell', 600, NOW());
INSERT INTO products (name, price, create_at) VALUES ('Nike', 650, NOW());
INSERT INTO products (name, price, create_at) VALUES ('Adidas', 450, NOW());
INSERT INTO products (name, price, create_at) VALUES ('Puma', 300, NOW());
INSERT INTO products (name, price, create_at) VALUES ('Reebok', 1200, NOW());
